name = "OpticalWavefronts"
uuid = "b2b24169-95b9-4fa9-9d7a-9bea57e8b16f"
authors = ["Ryan Dungee <ryan.dungee@utoronto.ca> and contributors"]
version = "0.1.0"

[deps]


[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
